version: '2'

services:
  agent:
    image: gocd/gocd-agent:16.12.0
    depends_on:
      - server
    environment:
      GO_SERVER: server
      AGENT_KEY: 079e578b-87cc-46c9-9ab5-88997fc7ac59
    volumes:
      - ~/.ssh:/var/go/.ssh

  server:
    image: gocd/gocd-server:16.12.0
    volumes:
      - ./build/libs/go-cd-git-path-material-plugin-1.3-SNAPSHOT.jar:/plugins/go-cd-git-path-material-plugin-1.3-SNAPSHOT.jar
      - ./extras/yaml-config-plugin-0.1.0.jar:/plugins/yaml-config-plugin-0.1.0.jar
      - ./extras/config.xml:/etc/go/cruise-config.xml
      - ~/.ssh:/var/go/.ssh
    ports:
      - "8153:8153"
      - "8154:8154"
